
name: GIT

on:
  workflow_run:
    workflows: [".NET"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: setup repo and dll file
      run: |
        mkdir ./output
        git clone https://github.com/N-E-W-T-O-N-S/unity-api.git ./output
        cp bin/Debug/netstandard2.1/NEWTONS.dll /output
    - name: push to repo
      uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
      env:
        SSH_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      with:
        source-directory: ./output
        destination-github-username: 'N-E-W-T-O-N-S'
        destination-repository-name: 'unity-api'
        user-email: $secrets.DEPLOY_EMAIL
        commit-message: automated dll update
        target-branch: main
